services:
  mongo:
    image: mongo:8
    ports: ["27017:27017"]
    healthcheck:
      test: ["CMD-SHELL","mongosh --quiet --eval 'db.runCommand({ ping: 1 }).ok' --host localhost:27017 | grep 1"]
      interval: 5s
      timeout: 5s
      retries: 10
